apps/core/urls.py
from django.urls import path

from apps.core.views import HomeView

urlpatterns = [
    
    path('', HomeView.as_view(),  name='home'),
    
]

apps/pessoas/urls.py
from django.urls import path

from apps.pessoas.views import *

urlpatterns = [
    path('list', PessoaListView.as_view(), name='pessoa_list'),
    path('create', PessoaCreateView.as_view(), name='pessoa_create'),
    path('detail/<int:pk>', PessoaDetailView.as_view(), name='pessoa_detail'),
    path('update/<int:pk>', PessoaUpdateView.as_view(), name='pessoa_update'),
    path('delete/<int:pk>', PessoaDeleteView.as_view(), name='pessoa_delete'),

]

apps/treinamentos/urls.py
from django.urls import path

from apps.treinamentos.views import create_treinamento

app_name = 'treinamentos'

urlpatterns = [
    # path('list', PerguntaListView.as_view(),  name='pergunta_list'),
    path('create/<int:pessoa_id>', create_treinamento, name='treinamento_create'),
    # path('detail/<int:pk>', PerguntaDetailView.as_view(),  name='pergunta_detail'),
    # path('update/<int:pk>', TreinamentoUpdateView.as_view(),  name='treinamento_update'),
    # path('delete/<int:pk>', PerguntaDeleteView.as_view(),  name='pergunta_delete'),

]

tcc/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.core.urls')),
    path('pessoas/', include('apps.pessoas.urls')),
    path('treinamentos/', include('apps.treinamentos.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/core/models.py
from django.db import models

# Create your models here.

apps/pessoas/models.py
from django.db import models
from django.urls import reverse

SEXO_CHOICES = (
    ('M', 'Masculino'),
    ('F', 'Feminino'),
    ('O', 'Outros'),
)


class Pessoa(models.Model):
    nome = models.CharField(max_length=50, unique=True)
    data_de_nascimento = models.DateField()
    sexo = models.CharField(max_length=1, choices=SEXO_CHOICES, default='M')
    imagem = models.ImageField(upload_to='pessoas', null=True, blank=True)

    class Meta:
        ordering = ['nome', ]
        verbose_name = 'Pessoa'
        verbose_name_plural = 'Pessoas'

    def __str__(self):
        return self.nome
    
    def get_sexo(self):
        if self.sexo == 'M':
            return 'Masculino'
        elif self.sexo == 'F':
            return 'Feminino'
        else:
            return 'Outros'

    def get_absolute_url(self):
        return reverse("pessoa_detail", kwargs={"pk": self.pk})

apps/treinamentos/models.py
from django.db import models

from apps.pessoas.models import Pessoa


class Treinamento(models.Model):
    pessoa = models.ForeignKey(Pessoa, on_delete=models.CASCADE)
    treinamento = models.CharField(max_length=50)
    imagem = models.ImageField(upload_to='treinamentos', null=True, blank=True)

    def __str__(self):
        return self.treinamento

    class Meta:
        verbose_name = 'Treinamento'
        verbose_name_plural = 'Treinamentos'

apps/core/views.py
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = "core/home.html"

apps/pessoas/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView

from apps.pessoas.models import Pessoa


class PessoaListView(ListView):
    model = Pessoa
    template_name = 'pessoas/pessoa_list.html'
    
    def get_queryset(self):
        valor = self.request.GET.get('q')
        if valor:
            object_list = self.model.objects.filter(
                Q(nome__icontains=valor) |
                Q(data_de_nascimento__icontains=valor) |
                Q(sexo__icontains=valor)
            )
        else:
            object_list = self.model.objects.all()

        paginator = Paginator(object_list, 6)  # Show n produtos per page

        page = self.request.GET.get('page')
        try:
            queryset = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            queryset = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            queryset = paginator.page(paginator.num_pages)
        
        return queryset


class PessoaCreateView(SuccessMessageMixin, CreateView):
    model = Pessoa
    fields = ['nome', 'data_de_nascimento', 'sexo', 'imagem', ]
    success_message = 'O registro de  %(nome)s foi criado com sucesso!'
    

class PessoaDetailView(DetailView):
    model = Pessoa


class PessoaUpdateView(SuccessMessageMixin, UpdateView):
    model = Pessoa
    fields = ['nome', 'data_de_nascimento', 'sexo', 'imagem', ]
    success_message = 'O registro de %(nome)s foi atualizado com sucesso!'


class PessoaDeleteView(SuccessMessageMixin, DeleteView):
    model = Pessoa
    success_url = reverse_lazy('pessoa_list')

apps/treinamentos/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.forms import inlineformset_factory
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import CreateView, UpdateView

from apps.pessoas.models import Pessoa
from apps.treinamentos.models import Treinamento


def create_treinamento(request, pessoa_id):
    pessoa = Pessoa.objects.get(id=pessoa_id)
    TreinamentoFormset = inlineformset_factory(Pessoa, Treinamento,
                                               fields=('treinamento', 'imagem', ),
                                               can_delete=True, extra=1)
    
    if request.method == 'POST':
        formset = TreinamentoFormset(request.POST, instance=pessoa)
        if formset.is_valid():
            formset.save()
            
            redirect('treinamentos/treinamento_form.html', pessoa_id=pessoa.id)
    
    formset = TreinamentoFormset(instance=pessoa)
    
    return render(request, 'treinamentos/treinamento_form.html', {'pessoa': pessoa,
                                                                  'formset':  formset})

apps/core/templates/core/home.html
{% extends 'base.html' %}

{% block content %}

    <div class="jumbotron mb-1 bg-primary text-light">
      <h1 class="display-4 text-center">TCC</h1>
      <p class="lead text-center">Maurício Andrade</p>
      <hr class="my-4">
      <p class="display-4 text-center">Pessoas x Treinamentos</p>

      <div class="container">
        <div class="row">
          <div class="col text-success"><i class="fas fa-smile fa-10x"></i></div>
          <div class="col text-warning"><i class="fas fa-frown fa-10x"></i></div>
          <div class="col text-danger"><i class="fas fa-angry fa-10x"></i></div>
        </div>
      </div>

    </div>


{% endblock %}

apps/pessoas/templates/pessoas/pessoa_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<h5>Apaga registro</h5>
<form method="post">{% csrf_token %}
    <p>Tem certeza que quer apagar o registro "{{ object }}"?</p>
    <input type="submit" value="Confirma" class="btn btn-danger btn-block">
</form>
    <a href="{{ object.get_absolute_url }}" class="btn btn-success btn-block">Voltar</a>
{% endblock %}

apps/pessoas/templates/pessoas/pessoa_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="container">
        <div class="row align-middle">
            <div class="col-md-6 ">
                <h5>Detalhe da Pessoa</h5>
            </div>
            <div class="col-md-6 ">
                <a href="{% url 'pessoa_list' %}" class="btn btn-outline-primary">
                    <i class="fas fa-arrow-alt-circle-left"></i>
                    Voltar
                </a>
            </div>
        </div>
    </div>

<div class="container">
    <div class="row">
        <div class="col-md-4">
            <div class="card" style="width: 18rem;">
                <img src="{% if object.imagem %}{{ object.imagem.url }}{% else %} {% static 'img/no_image_found.png' %} {% endif %}"
                        class="card-img-top" alt="...">

                <ul class="list-group list-group-flush">
                    <li class="list-group-item">Id.: {{object.id}}</li>
                    <li class="list-group-item">Nome: {{object.nome}}</li>
                    <li class="list-group-item">Data de Nascimento: {{object.data_de_nascimento|date:"d/m/Y"}}</li>
                    <li class="list-group-item">Sexo: {{object.get_sexo}}</li>
                </ul>

            </div>
        </div>


        {% if object.treinamento_set.all %}
        <div class="col-md-6 border">
            <h6 class="text-info">Treinamentos realizados por <strong>{{object.nome}}</strong></h6>
            <div class="table-responsive-sm">
                <table class="table table-sm table-striped table-hover table-bordered">
                  <thead class="thead-dark">
                    <tr>
                      <th>Nome do Treinamento</th>
                      <th class="text-center">Imagem</th>

                    </tr>
                  </thead>
                  <tbody>

                <div class="container">
                {% for treino in object.treinamento_set.all %}
                   <tr>
                       <td class="align-middle">
                          {{ treino.treinamento }}
                       </td>
                       <td class="align-middle text-center">
                      <img src="{% if treino.imagem %}
                                    {{ treino.imagem.url }}
                              {% else %}
                                    {% static 'img/no_image_found.png' %}
                              {% endif %}"
                         alt="Responsive image" class="img-thumbnail img-fluid"
                            width="50" height="50">
                       </td>
                   </tr>
                {% endfor %}
                   </tbody>
                    </table>
                </div>
                </div>
        {% endif%}
        </div>
    </div>
</div>


{% endblock %}


<!--
<div class="card" style="width: 18rem;">
  <img src="..." class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">Card title</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Cras justo odio</li>
    <li class="list-group-item">Dapibus ac facilisis in</li>
    <li class="list-group-item">Vestibulum at eros</li>
  </ul>
  <div class="card-body">
    <a href="#" class="card-link">Card link</a>
    <a href="#" class="card-link">Another link</a>
  </div>
</div>

apps/pessoas/templates/pessoas/pessoa_form.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{% block content %}
    <h1>Pessoa</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-outline-success btn-block">
                Gravar
            </button>
        {% endbuttons %}
    </form>

    {% if object %}
        <a href="{% url 'treinamentos:treinamento_create' pessoa_id=object.id %}"
        class="btn btn-outline-primary btn-block">
            Adicionar Treinamentos
        </a>
    {% endif %}


{% endblock %}

apps/pessoas/templates/pessoas/pessoa_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="container mb-2">
        <div class="row border">
            <div class="col-4 ">
                <h5>Pessoas</h5>
            </div>
            <div class="col">
                <a href="{% url 'pessoa_create' %}" class="btn btn-outline-success">
                    <i class="fas fa-plus-circle"></i>
                    Criar Nova Pessoa</a>
            </div>
            <div class="col">
                <!-- pagination -->
            <nav aria-label="Page navigation example">
              <ul class="pagination pagination-sm justify-content-end">

                {% if object_list.has_previous %}
                <li class="page-item"><a class="page-link" href="?page={{ object_list.previous_page_number }}&q={{ request.GET.q }}"><i class="fas fa-chevron-circle-left"></i> Anterior</a></li>
                {% endif %}

                <li class="page-item active">
                    <span class="page-link">
                            Página {{ object_list.number }} de {{ object_list.paginator.num_pages }}
                            <span class="sr-only">(current)</span>
                    </span>
                </li>

                {% if object_list.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ object_list.next_page_number }}&q={{ request.GET.q }}"><i class="fas fa-chevron-circle-right"></i> Próxima</a></li>
                {% endif %}

              </ul>
            </nav>
            <!--end of pagination-->
            </div>
        </div>
    </div>
<div class="container border">
    <div class="table-responsive-sm">
    <table class="table table-sm table-striped table-hover table-bordered">
      <thead class="thead-dark">
        <tr>
          <th class="text-center">Imagem</th>
          <th class="text-center">Id.</th>
          <th >Pessoa</th>
          <th class="text-center">Treinamentos</th>
          <th class="text-center text-info">Detalhe</th>
          <th class="text-center text-warning">Atualiza</th>
          <th class="text-center text-danger">Apaga</th>
        </tr>
      </thead>
      <tbody>
    {% for pessoa in object_list %}
        <tr>
            <td class="align-middle text-center"><img src="{% if pessoa.imagem %}
                                {{ pessoa.imagem.url }}
                          {% else %}
                                {% static 'img/no_image_found.png' %}
                          {% endif %}"
                     alt="Responsive image" class="img-thumbnail img-fluid"
                        width="50" height="50">
            </td>
            <td class="align-middle text-center">{{ pessoa.id }}</td>
            <td class="align-middle">{{ pessoa.nome }}</td>
            <td class={% if pessoa.treinamento_set.count %} "align-middle text-center bg-warning"
                      {% else %}
                        "align-middle text-center bg-success"
                      {% endif %}>
                <span class="badge badge-warning">
                    {{ pessoa.treinamento_set.count }} realizado{{ pessoa.treinamento_set.count|pluralize }}
                </span>
            </td>
            <td class="align-middle text-center"><a href="{% url 'pessoa_detail' pessoa.id %}"><i class="fas fa-eye text-info" ></i></a></td>
            <td class="align-middle text-center"><a href="{% url 'pessoa_update' pessoa.id %}"><i class="fas fa-edit text-warning"></i></a></td>
            <td class="align-middle text-center"><a href="{% url 'pessoa_delete' pessoa.id %}"><i class="fas fa-trash-alt text-danger"></i></a></td>
        </tr>
    {% empty %}
        <li>Nenhuma pessoa ainda.</li>
    {% endfor %}
      </tbody>
    </table>
</div>
    </div>
{% endblock %}

apps/treinamentos/templates/treinamentos/treinamento_form.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{% block content %}
    <div class="container d-flex justify-content-center ">
        <div class="row">
            <div class="col">
                <h4 class="text-center">Treinamentos</h4>
            </div>
            <div class="col">
                <a href="{% url 'pessoa_list' %}"
                   class="btn btn-outline-primary btn-sm">
                    <i class="fas fa-arrow-alt-circle-left"></i>
                    Voltar</a>
            </div>
        </div>
    </div>


    <div class="container d-flex justify-content-center">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="col border">
                {% bootstrap_formset formset layout='horizontal' %}
                </div>
                {% buttons %}
                    <button type="submit"
                            class="btn btn-outline-success btn-block">
                        <i class="fas fa-save"></i>
                        Gravar
                    </button>
                {% endbuttons %}
            </form>
    </div>
{% endblock %}

templates/base.html
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Fontawesome CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.2/css/all.min.css">

    <!-- Bootstrap CSS - LOCAL -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">


      <!-- Bootstrap CSS -->
<!--
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
-->

    <title>TCC</title>
  </head>
  <body>

        <div class="container">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <a class="navbar-brand" href="{% url 'home' %}">TCC</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                  aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                  <li class="nav-item active">
                      <a class="nav-link" href="{% url 'home' %}">Início <span class="sr-only">(current)</span></a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'pessoa_list' %}">Lista de Pessoas</a>
                  </li>


              </ul>
              <form class="form-inline my-2 my-lg-0">
                  <input class="form-control mr-sm-2"
                         id="searchbox"
                         name="q"
                         type="text"
                         value="{{ request.GET.q }}"
                         placeholder="Pesquise por Pessoas..." aria-label="Search">

                  <button class="btn btn-success my-2 my-sm-0" type="submit">Pesquisa</button>
              </form>
          </div>
      </nav>

      </div>

        <div class="container">
            {% include 'messages.html' %}
            {% block content %}
            {% endblock %}
        </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

templates/messages.html
{% for message in messages %}
  <div class="alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
{% endfor %}